VeterLabParcial/Controllers/RecepcionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VeterLabParcial.Models;

namespace VeterLabParcial.Controllers
{
    public class RecepcionsController : Controller
    {
        private VeterLabParcialEntities db = new VeterLabParcialEntities();

        // GET: Recepcions
        public ActionResult Index()
        {
            var recepcion = db.Recepcion.Include(r => r.Cliente).Include(r => r.Laboratorio);
            return View(recepcion.ToList());
        }

        // GET: Recepcions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recepcion recepcion = db.Recepcion.Find(id);
            if (recepcion == null)
            {
                return HttpNotFound();
            }
            return View(recepcion);
        }

        // GET: Recepcions/Create
        public ActionResult Create()
        {
            ViewBag.IdCli = new SelectList(db.Cliente, "Id", "Nombre");
            ViewBag.IdLab = new SelectList(db.Laboratorio, "Id", "Nombre");
            return View();
        }

        // POST: Recepcions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IdCli,IdLab,Folio,FechaRecepcion,FechaEntrega,Localidad,CantidadMuestra")] Recepcion recepcion)
        {
            if (ModelState.IsValid)
            {
                db.Recepcion.Add(recepcion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCli = new SelectList(db.Cliente, "Id", "Nombre", recepcion.IdCli);
            ViewBag.IdLab = new SelectList(db.Laboratorio, "Id", "Nombre", recepcion.IdLab);
            return View(recepcion);
        }

        // GET: Recepcions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recepcion recepcion = db.Recepcion.Find(id);
            if (recepcion == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCli = new SelectList(db.Cliente, "Id", "Nombre", recepcion.IdCli);
            ViewBag.IdLab = new SelectList(db.Laboratorio, "Id", "Nombre", recepcion.IdLab);
            return View(recepcion);
        }

        // POST: Recepcions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdCli,IdLab,Folio,FechaRecepcion,FechaEntrega,Localidad,CantidadMuestra")] Recepcion recepcion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recepcion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCli = new SelectList(db.Cliente, "Id", "Nombre", recepcion.IdCli);
            ViewBag.IdLab = new SelectList(db.Laboratorio, "Id", "Nombre", recepcion.IdLab);
            return View(recepcion);
        }

        // GET: Recepcions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recepcion recepcion = db.Recepcion.Find(id);
            if (recepcion == null)
            {
                return HttpNotFound();
            }
            return View(recepcion);
        }

        // POST: Recepcions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recepcion recepcion = db.Recepcion.Find(id);
            db.Recepcion.Remove(recepcion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VeterLabParcial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VeterLab", "Index", "Recepcions", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                    <li>@Html.ActionLink("Laboratorios", "Index", "Laboratorios")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VeterLab</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>